/* empty css                      */import{a as S,S as v,i}from"./assets/vendor-C87Qbf8s.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const q="https://pixabay.com/api/",$="51380954-6619e500596c0682c7775fe9d",C=15;async function m(r,e=1){try{return(await S(q,{params:{key:$,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:C}})).data}catch(s){console.log(s.message)}}const f=document.querySelector(".gallery"),p=document.querySelector(".loader"),h=document.querySelector(".js-load-more");let M=new v(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const e=r.map(({webformatURL:s,largeImageURL:c,tags:t,likes:o,views:a,comments:L,downloads:w})=>`
        <li class="gallery-item">
          <a href="${c}">
            <img src="${s}" alt="${t}" loading="lazy" />
          </a>
          <div class="info">
            <p><b>Likes</b> ${o}</p>
            <p><b>Views</b> ${a}</p>
            <p><b>Comments</b> ${L}</p>
            <p><b>Downloads</b> ${w}</p>
          </div>
        </li>
      `).join("");f.insertAdjacentHTML("beforeend",e),M.refresh()}function P(){f.innerHTML=""}function g(){p.classList.remove("hidden")}function b(){p.classList.add("hidden")}function B(){h.classList.remove("load-more-hidden")}function d(){h.classList.add("load-more-hidden")}const E=document.querySelector(".form"),H=document.querySelector(".js-load-more");let n=1,u=0,l="";E.addEventListener("submit",O);H.addEventListener("click",x);async function O(r){if(r.preventDefault(),l=r.currentTarget.elements["search-text"].value.trim().toLowerCase(),!l){i.error({message:"Please enter the search",position:"bottomCenter"});return}n=1,u=0,P(),g(),d();try{const e=await m(l,n);if(u=e.totalHits,!e.hits.length){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"bottomCenter"});return}y(e.hits),e.totalHits>n*15?B():d()}catch(e){i.error({message:`Something went wrong: ${e.message}`,position:"bottomCenter"})}finally{b()}}async function x(){n++,g();try{const r=await m(l,n);y(r.hits);const e=document.querySelector(".gallery-item");if(e){const{height:s}=e.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}n*15>=u&&(d(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"}))}catch(r){i.error({message:`Something went wrong: ${r.message}`,position:"bottomCenter"})}finally{b()}}
//# sourceMappingURL=index.js.map
